"""Verify generated bytes against the accepted canonical geometry; no new geometry rules."""

from io import BytesIO, StringIO
import json
import math
import ezdxf
from pypdf import PdfReader
from plate_geometry import rough_bore_diameter, manufacturing_record


def validate_package(g, metadata, outputs):
    if set(outputs) != {"pdf", "dxf", "json"}:
        raise ValueError("incomplete manufacturing package")
    doc = ezdxf.read(StringIO(outputs["dxf"].decode("ascii")))
    audit = doc.audit()
    if audit.errors or audit.fixes or doc.units != 1:
        raise ValueError("DXF audit/units failed")
    entities = list(doc.modelspace())
    if len(entities) != (3 if g.spec.handle_hole_enabled else 2):
        raise ValueError("unexpected cutting entities")
    outer, bore = entities[:2]
    if (
        outer.dxftype() != "LWPOLYLINE"
        or not outer.closed
        or outer.dxf.layer != "CUT_OUTER"
        or bore.dxftype() != "CIRCLE"
        or bore.dxf.layer != "CUT_BORE"
    ):
        raise ValueError("invalid cutting profiles")

    def close(a, b):
        return math.isclose(a, b, rel_tol=0, abs_tol=1e-12)

    if len(outer) != len(g.outer_vertices_xyb) or any(
        not close(a, b)
        for actual, expected in zip(outer.get_points("xyb"), g.outer_vertices_xyb)
        for a, b in zip(actual, expected)
    ):
        raise ValueError("outer geometry differs from frozen specification")
    if not close(bore.dxf.radius * 2, rough_bore_diameter(g.spec)) or tuple(
        bore.dxf.center
    ) != (0, 0, 0):
        raise ValueError("rough bore differs from canonical rule")
    if g.spec.handle_hole_enabled:
        hole = entities[2]
        if (hole.dxftype() != "CIRCLE" or hole.dxf.layer != "CUT_HANDLE_HOLE"
            or not close(hole.dxf.radius * 2, g.spec.handle_hole_diameter)
            or not close(hole.dxf.center.x, g.spec.centerline_to_handle_end - g.spec.handle_hole_center_from_handle_end)
            or tuple(hole.dxf.center)[1:] != (0, 0)):
            raise ValueError("Handle hole differs from frozen finished dimensions")
    record = json.loads(outputs["json"])
    expected = json.loads(json.dumps(manufacturing_record(g)))
    if any(record[k] != v for k, v in expected.items() if k != "status"):
        raise ValueError("JSON specification/geometry mismatch")
    from dataclasses import asdict

    if record["drawing"] != asdict(metadata):
        raise ValueError("drawing metadata mismatch")
    reader = PdfReader(BytesIO(outputs["pdf"]), strict=True)
    if len(reader.pages) != 1:
        raise ValueError("expected one drawing sheet")
    text = reader.pages[0].extract_text()
    if g.spec.handle_hole_enabled:
        for label in (f"HANDLE HOLE Ø{g.spec.handle_hole_diameter:.4f}",
                      f"{g.spec.handle_hole_center_from_handle_end:.4f} HANDLE END TO HOLE C/L"):
            if label not in text:
                raise ValueError("PDF missing finished handle hole requirement")
    for label in (
        f"Ø{g.spec.finished_bore_diameter:.3f}",
        "OP-" + g.spec.part_identifier,
        metadata.revision,
        "CUSTOMER CONFIRMATION",
    ):
        if label not in text:
            raise ValueError(
                "PDF missing finished requirement or revision identity: " + label
            )
